import { Inter } from "next/font/google";
import Navbar from "@/app/components/navbar";
import Sidenav from "@/app/components/sidenav/sidenav";
import styles from "./globals.css"
import {Suspense} from "react";
import Loading from "@/app/components/loading";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
      <html lang="en">
      <body className={inter.className}>
      <Navbar/>
      <div className={"general-con"}>
        <Sidenav />
        <Suspense fallback={<div>Loading...</div>}>
          {children}
        </Suspense>
      </div>
      </body>
      </html>
  );
}
